#pragma once
#include "macros.h"
#include <avr/io.h>

#define port_b_input_mode(...) unset_flags(DDRB, __VA_ARGS__); unset_flags(PORTB, __VA_ARGS__)
#define port_c_input_mode(...) unset_flags(DDRC, __VA_ARGS__); unset_flags(PORTC, __VA_ARGS__)
#define port_d_input_mode(...) unset_flags(DDRD, __VA_ARGS__); unset_flags(PORTD, __VA_ARGS__)
#define port_b_pullup_input_mode(...) unset_flags(DDRB, __VA_ARGS__); set_flags(PORTB, __VA_ARGS__)
#define port_c_pullup_input_mode(...) unset_flags(DDRC, __VA_ARGS__); set_flags(PORTC, __VA_ARGS__)
#define port_d_pullup_input_mode(...) unset_flags(DDRD, __VA_ARGS__); set_flags(PORTD, __VA_ARGS__)
#define port_b_read(bit) (!!check_flag(PINB, bit))
#define port_c_read(bit) (!!check_flag(PINC, bit))
#define port_d_read(bit) (!!check_flag(PIND, bit))
#define port_b_output_mode(...) set_flags(DDRB, __VA_ARGS__)
#define port_c_output_mode(...) set_flags(DDRC, __VA_ARGS__)
#define port_d_output_mode(...) set_flags(DDRD, __VA_ARGS__)
#define port_b_write(bit, value) unset_flags(PORTB, bit); PORTB |= value << bit
#define port_c_write(bit, value) unset_flags(PORTC, bit); PORTC |= value << bit
#define port_d_write(bit, value) unset_flags(PORTD, bit); PORTD |= value << bit
#define port_b_high(...) set_flags(PORTB, __VA_ARGS__)
#define port_c_high(...) set_flags(PORTC, __VA_ARGS__)
#define port_d_high(...) set_flags(PORTD, __VA_ARGS__)
#define port_b_low(...) unset_flags(PORTB, __VA_ARGS__)
#define port_c_low(...) unset_flags(PORTC, __VA_ARGS__)
#define port_d_low(...) unset_flags(PORTD, __VA_ARGS__)

#define pb0_input_mode(...) port_b_input_mode(0)
#define pb1_input_mode(...) port_b_input_mode(1)
#define pb2_input_mode(...) port_b_input_mode(2)
#define pb3_input_mode(...) port_b_input_mode(3)
#define pb4_input_mode(...) port_b_input_mode(4)
#define pb5_input_mode(...) port_b_input_mode(5)
#define pb6_input_mode(...) port_b_input_mode(6)
#define pb7_input_mode(...) port_b_input_mode(7)
#define pc0_input_mode(...) port_c_input_mode(0)
#define pc1_input_mode(...) port_c_input_mode(1)
#define pc2_input_mode(...) port_c_input_mode(2)
#define pc3_input_mode(...) port_c_input_mode(3)
#define pc4_input_mode(...) port_c_input_mode(4)
#define pc5_input_mode(...) port_c_input_mode(5)
#define pc6_input_mode(...) port_c_input_mode(6)
#define pc7_input_mode(...) port_c_input_mode(7)
#define pd0_input_mode(...) port_d_input_mode(0)
#define pd1_input_mode(...) port_d_input_mode(1)
#define pd2_input_mode(...) port_d_input_mode(2)
#define pd3_input_mode(...) port_d_input_mode(3)
#define pd4_input_mode(...) port_d_input_mode(4)
#define pd5_input_mode(...) port_d_input_mode(5)
#define pd6_input_mode(...) port_d_input_mode(6)
#define pd7_input_mode(...) port_d_input_mode(7)

#define pb0_pullup_input_mode(...) port_b_pullup_input_mode(0)
#define pb1_pullup_input_mode(...) port_b_pullup_input_mode(1)
#define pb2_pullup_input_mode(...) port_b_pullup_input_mode(2)
#define pb3_pullup_input_mode(...) port_b_pullup_input_mode(3)
#define pb4_pullup_input_mode(...) port_b_pullup_input_mode(4)
#define pb5_pullup_input_mode(...) port_b_pullup_input_mode(5)
#define pb6_pullup_input_mode(...) port_b_pullup_input_mode(6)
#define pb7_pullup_input_mode(...) port_b_pullup_input_mode(7)
#define pc0_pullup_input_mode(...) port_c_pullup_input_mode(0)
#define pc1_pullup_input_mode(...) port_c_pullup_input_mode(1)
#define pc2_pullup_input_mode(...) port_c_pullup_input_mode(2)
#define pc3_pullup_input_mode(...) port_c_pullup_input_mode(3)
#define pc4_pullup_input_mode(...) port_c_pullup_input_mode(4)
#define pc5_pullup_input_mode(...) port_c_pullup_input_mode(5)
#define pc6_pullup_input_mode(...) port_c_pullup_input_mode(6)
#define pc7_pullup_input_mode(...) port_c_pullup_input_mode(7)
#define pd0_pullup_input_mode(...) port_d_pullup_input_mode(0)
#define pd1_pullup_input_mode(...) port_d_pullup_input_mode(1)
#define pd2_pullup_input_mode(...) port_d_pullup_input_mode(2)
#define pd3_pullup_input_mode(...) port_d_pullup_input_mode(3)
#define pd4_pullup_input_mode(...) port_d_pullup_input_mode(4)
#define pd5_pullup_input_mode(...) port_d_pullup_input_mode(5)
#define pd6_pullup_input_mode(...) port_d_pullup_input_mode(6)
#define pd7_pullup_input_mode(...) port_d_pullup_input_mode(7)

#define pb0_read(...) port_b_read(0)
#define pb1_read(...) port_b_read(1)
#define pb2_read(...) port_b_read(2)
#define pb3_read(...) port_b_read(3)
#define pb4_read(...) port_b_read(4)
#define pb5_read(...) port_b_read(5)
#define pb6_read(...) port_b_read(6)
#define pb7_read(...) port_b_read(7)
#define pc0_read(...) port_c_read(0)
#define pc1_read(...) port_c_read(1)
#define pc2_read(...) port_c_read(2)
#define pc3_read(...) port_c_read(3)
#define pc4_read(...) port_c_read(4)
#define pc5_read(...) port_c_read(5)
#define pc6_read(...) port_c_read(6)
#define pc7_read(...) port_c_read(7)
#define pd0_read(...) port_d_read(0)
#define pd1_read(...) port_d_read(1)
#define pd2_read(...) port_d_read(2)
#define pd3_read(...) port_d_read(3)
#define pd4_read(...) port_d_read(4)
#define pd5_read(...) port_d_read(5)
#define pd6_read(...) port_d_read(6)
#define pd7_read(...) port_d_read(7)

#define pb0_output_mode(...) port_b_output_mode(0)
#define pb1_output_mode(...) port_b_output_mode(1)
#define pb2_output_mode(...) port_b_output_mode(2)
#define pb3_output_mode(...) port_b_output_mode(3)
#define pb4_output_mode(...) port_b_output_mode(4)
#define pb5_output_mode(...) port_b_output_mode(5)
#define pb6_output_mode(...) port_b_output_mode(6)
#define pb7_output_mode(...) port_b_output_mode(7)
#define pc0_output_mode(...) port_c_output_mode(0)
#define pc1_output_mode(...) port_c_output_mode(1)
#define pc2_output_mode(...) port_c_output_mode(2)
#define pc3_output_mode(...) port_c_output_mode(3)
#define pc4_output_mode(...) port_c_output_mode(4)
#define pc5_output_mode(...) port_c_output_mode(5)
#define pc6_output_mode(...) port_c_output_mode(6)
#define pc7_output_mode(...) port_c_output_mode(7)
#define pd0_output_mode(...) port_d_output_mode(0)
#define pd1_output_mode(...) port_d_output_mode(1)
#define pd2_output_mode(...) port_d_output_mode(2)
#define pd3_output_mode(...) port_d_output_mode(3)
#define pd4_output_mode(...) port_d_output_mode(4)
#define pd5_output_mode(...) port_d_output_mode(5)
#define pd6_output_mode(...) port_d_output_mode(6)
#define pd7_output_mode(...) port_d_output_mode(7)

#define pb0_write(value) port_b_write(0, value)
#define pb1_write(value) port_b_write(1, value)
#define pb2_write(value) port_b_write(2, value)
#define pb3_write(value) port_b_write(3, value)
#define pb4_write(value) port_b_write(4, value)
#define pb5_write(value) port_b_write(5, value)
#define pb6_write(value) port_b_write(6, value)
#define pb7_write(value) port_b_write(7, value)
#define pc0_write(value) port_c_write(0, value)
#define pc1_write(value) port_c_write(1, value)
#define pc2_write(value) port_c_write(2, value)
#define pc3_write(value) port_c_write(3, value)
#define pc4_write(value) port_c_write(4, value)
#define pc5_write(value) port_c_write(5, value)
#define pc6_write(value) port_c_write(6, value)
#define pc7_write(value) port_c_write(7, value)
#define pd0_write(value) port_d_write(0, value)
#define pd1_write(value) port_d_write(1, value)
#define pd2_write(value) port_d_write(2, value)
#define pd3_write(value) port_d_write(3, value)
#define pd4_write(value) port_d_write(4, value)
#define pd5_write(value) port_d_write(5, value)
#define pd6_write(value) port_d_write(6, value)
#define pd7_write(value) port_d_write(7, value)

#define pb0_high(...) port_b_high(0)
#define pb1_high(...) port_b_high(1)
#define pb2_high(...) port_b_high(2)
#define pb3_high(...) port_b_high(3)
#define pb4_high(...) port_b_high(4)
#define pb5_high(...) port_b_high(5)
#define pb6_high(...) port_b_high(6)
#define pb7_high(...) port_b_high(7)
#define pc0_high(...) port_c_high(0)
#define pc1_high(...) port_c_high(1)
#define pc2_high(...) port_c_high(2)
#define pc3_high(...) port_c_high(3)
#define pc4_high(...) port_c_high(4)
#define pc5_high(...) port_c_high(5)
#define pc6_high(...) port_c_high(6)
#define pc7_high(...) port_c_high(7)
#define pd0_high(...) port_d_high(0)
#define pd1_high(...) port_d_high(1)
#define pd2_high(...) port_d_high(2)
#define pd3_high(...) port_d_high(3)
#define pd4_high(...) port_d_high(4)
#define pd5_high(...) port_d_high(5)
#define pd6_high(...) port_d_high(6)
#define pd7_high(...) port_d_high(7)

#define pb0_low(...) port_b_low(0)
#define pb1_low(...) port_b_low(1)
#define pb2_low(...) port_b_low(2)
#define pb3_low(...) port_b_low(3)
#define pb4_low(...) port_b_low(4)
#define pb5_low(...) port_b_low(5)
#define pb6_low(...) port_b_low(6)
#define pb7_low(...) port_b_low(7)
#define pc0_low(...) port_c_low(0)
#define pc1_low(...) port_c_low(1)
#define pc2_low(...) port_c_low(2)
#define pc3_low(...) port_c_low(3)
#define pc4_low(...) port_c_low(4)
#define pc5_low(...) port_c_low(5)
#define pc6_low(...) port_c_low(6)
#define pc7_low(...) port_c_low(7)
#define pd0_low(...) port_d_low(0)
#define pd1_low(...) port_d_low(1)
#define pd2_low(...) port_d_low(2)
#define pd3_low(...) port_d_low(3)
#define pd4_low(...) port_d_low(4)
#define pd5_low(...) port_d_low(5)
#define pd6_low(...) port_d_low(6)
#define pd7_low(...) port_d_low(7)
